### ISSUE TITLE
$prop pass into variable why sometimes has colon in front, sometimes has no colon

### ISSUE THREAD

**Issue by ericxin1982** [vimeshjs/vimesh-ui#11]
![image](https://github.com/vimeshjs/vimesh-ui/assets/9047436/d6bb9d19-42fb-4262-81ef-df507cccbaf4)

Hi @xinjie-zhang 

When the colon should be used, I am puzzled, would you please instruct me a bit more?

Thanks
Eric Xin

**Comment by xinjie-zhang** [comment]
It is shorthand syntax of alphin.js x-bind directive, please refer to https://alpinejs.dev/directives/bind

**Comment by ericxin1982** [comment]
Thanks for your help, I read again, and I thought I understood already.
