### ISSUE TITLE
$api why there

### ISSUE THREAD

**Issue by ericxin1982** [vimeshjs/vimesh-ui#13]
![image](https://github.com/vimeshjs/vimesh-ui/assets/9047436/5993a184-d3b3-4173-a0a0-b7c8a3840052)

HI @xinjie-zhang 

I understood $api.init(), since init() is defined inside script, and why need to write $api && $api.init() together, what is the purpose of using $api that way?

Thanks
Eric Xin

**Comment by xinjie-zhang** [comment]
When x-init is executing, the $api may not exist, $api && $api.init() will ensure $api has been created.
