### ISSUE TITLE
different namespace how to import together

### ISSUE THREAD

**Issue by ericxin1982** [vimeshjs/vimesh-ui#15]
![image](https://github.com/vimeshjs/vimesh-ui/assets/9047436/bcf9fe21-33f0-4307-9ef6-ca4369d5f5ac)

Hi @xinjie-zhang 

I saw a case like this, that means imports app folder, different html file, if want to import app folder, page folder different html files together, how to do, is it possible?

Thanks
Eric Xin

**Comment by xinjie-zhang** [comment]
You could seperate different namespace with ";". For example x-import = "app:header,footer;page:home,users;hui:tabs"
