### ISSUE TITLE
$vui and its method and vscode support

### ISSUE THREAD

**Issue by ericxin1982** [vimeshjs/vimesh-ui#16]
HI @xinjie-zhang 

Is there somewhere I can learn more about $vui and its methods or attributes, and does it support well inside vscode?

Thanks
Eric Xin

**Comment by xinjie-zhang** [comment]
I add introduction of $vui in README. Anyway, you could find its implementation in src/core.js and src/x-component.js

**Comment by ericxin1982** [comment]
Thanks
