### ISSUE TITLE
Method $vui.getParentComponent(element) return void

### ISSUE THREAD

**Issue by boolboost** [vimeshjs/vimesh-ui#22]
There is clearly a need for return, otherwise the method is meaningless.

https://github.com/vimeshjs/vimesh-ui/blob/a41146fb331fbaf7d259bedabfb25ece9d720c2d/src/x-component.js#L49-L51

**Comment by xinjie-zhang** [comment]
Thanks, this is a bug introduced from v0.12.5. It is fixed.
