### ISSUE TITLE
How to load directives and magic when using npm module.

### ISSUE THREAD

**Issue by g5becks** [vimeshjs/vimesh-ui#5]
Hi, thanks for the great lib. I am attempting to use this library in a bundled that is being built with esbuild.

There is not mention of how to load the directives and magics when importing into a bundle. I tried following the instructions found [here](https://alpinejs.dev/advanced/extending#via-npm), but I couldn't get it to work.

Any help would be highly appreciated.

Thanks.

**Comment by xinjie-zhang** [comment]
Normally it is not a good practice to bundle Alpinejs. If you are using it with React, Vue or other frameworks, you have to understand most of these frameworks are based on virtual DOM not real DOM. Mix Alpinejs with React/Vue may cause unexpected issue. Anyway, could you share a minimal sample esbuild project of your problem?

**Comment by g5becks** [comment]
I decided on not bundling in the end. Thanks.
