### ISSUE TITLE
x-include and x-include.unwrap

### ISSUE THREAD

**Issue by ericxin1982** [vimeshjs/vimesh-ui#8]
Hi @xinjie-zhang , @vimeshjs 

Sorry to ask, since I cannot find answer myself.
What is the difference between x-include and x-include.unwrap?

Thanks
Eric Xin

**Comment by xinjie-zhang** [comment]
Add description about unwrap modifier in both x-include and x-component in README. It is used to remove external wrapper tag, which gives more controls of html element hierarchy.

**Comment by ericxin1982** [comment]
Thanks
