### ISSUE TITLE
$api usage

### ISSUE THREAD

**Issue by ericxin1982** [vimeshjs/vimesh-ui#9]
Hi @xinjie-zhang , @vimeshjs 

Would you please share me more detail about $api, it looks magic but complex.

Thanks
Eric Xin

**Comment by xinjie-zhang** [comment]
Yes. $api looks magic and is core of vimesh UI. You could study the source code for better understand the underlying mechanism. [vimesh-headless](https://github.com/vimeshjs/vimesh-headless) heavily uses $api. There are many examples about $api usage in real cases.

**Comment by ericxin1982** [comment]
Thanks
